fix: claimed and update polkadot api
debionetwork/debio-background-worker pull request #104
Opened 2022-06-28 15:06 UTC by rubenkristian

### JIRA LINK 🟦
- https://blocksphere2020.atlassian.net/browse/DBIO-2727

### Changelog/Description 🗒️
- update polkadot api
- fix country service request delete

### WARNING ⚠️
- 

### Screenshoot/Video (Optional) 🖼️
![image](https://user-images.githubusercontent.com/56469224/176463530-66d8cb0d-d721-44e0-afc5-1e0354c55591.png)

2022-06-28 17:28 UTC, agustinustheo requested changes
Please make integration testing for this.

2022-06-30 04:19 UTC, bukandicki submitted a review, later dismissed
Looks good, but i have a note for code quality

2022-06-30 04:19 UTC, bukandicki commented on src/substrate/events/service-request/commands/claimed-service-request/claimed-service-request.handler.ts
> +    if (service_request !== null) {
too many codes inside this `if` statement, please make it simpler by using the return instead

2022-06-30 04:19 UTC, bukandicki commented on src/substrate/events/service-request/commands/finalized-service-request/finalized-service-request.handler.ts
> +    if (service_request !== null) {
Same here too many codes inside this `if` statement, please make it simpler by using the return instead

2022-06-30 04:19 UTC, bukandicki commented on src/substrate/events/service-request/commands/processed-service-request/processed-service-request.handler.ts
> +    if (service_request !== null) {
too many codes inside this `if` statement, please make it simpler by using the return instead

2022-06-30 04:19 UTC, bukandicki commented on src/substrate/substrate.handler.ts
>      }
too many codes inside this `if` statement, please make it simpler by using the return instead

2022-07-01 06:44 UTC, agustinustheo approved these changes

2022-07-01 08:45 UTC, bukandicki commented
@rubenkristian I mean, instead of
```js
if(service_request !== null) {  ...a bunch of code }
```
make it simpler like this, not convert those code to a function
```js
if(service_request === null) return

 ... a bunch of code
```

2022-07-02 02:49 UTC, agustinustheo commented
> @rubenkristian I mean, instead of
> 
> ```js
> if(service_request !== null) {  ...a bunch of code }
> ```
> 
> make it simpler like this, not convert those code to a function
> 
> ```js
> if(service_request === null) return
> 
> // Move here please
>  ... a bunch of code
> ```

After pulling and reading the code, I see that this is fine and is more readable than your suggestion.

2022-07-02 03:01 UTC, merged