Substrate order event index to elasticsearch
debionetwork/debio-background-worker pull request #11
Opened 2021-09-06 15:03 UTC by rubenkristian

### Debio 667
url: [https://blocksphere2020.atlassian.net/browse/DBIO-667](https://blocksphere2020.atlassian.net/browse/DBIO-667)

### [Indexer] - Index Order data in substrate (debio-node)

Handle all event orders, create index for orders to elasticsearch, update index, reset all index when substrate reset.

2021-09-06 15:33 UTC, agustinustheo requested changes

2021-09-06 15:33 UTC, agustinustheo commented on src/substrate/orders/commands/order-fulfilled/order-fulfilled.handler.ts
> +      console.log(err);
I think it would be better to use a `Logger` rather than `console.log` on errors. Is it possible for you to change this?

2021-09-06 15:33 UTC, agustinustheo commented on src/substrate/orders/commands/order-paid/order-paid.handler.ts
> +      console.log(err);
I already commented on a similar issue, but there are multiple instances of this happening, can you please use `Logger` to log instead of `console.log`?

2021-09-06 15:33 UTC, agustinustheo commented on src/substrate/substrate.handler.ts
> +    // if(event.section === 'orders') {
I don't think the comments and the extra `console.log` are necessary, please delete them.

2021-09-07 06:09 UTC, kevinjanada commented on src/substrate/orders/commands/order-fulfilled/order-fulfilled.handler.ts
> +      console.log(err);
agree

2021-09-07 06:09 UTC, kevinjanada commented on src/substrate/orders/commands/order-paid/order-paid.handler.ts
> +      console.log(err);
agree

2021-09-07 06:09 UTC, kevinjanada commented on src/substrate/substrate.handler.ts
> +    // if(event.section === 'orders') {
agree

2021-09-07 09:20 UTC, kevinjanada approved these changes
LGTM

2021-09-07 13:23 UTC, agustinustheo approved these changes
Wonderful!

2021-09-07 13:23 UTC, agustinustheo commented
Absolutely wonderful! @rubenkristian

2021-09-07 13:24 UTC, merged