undo to process env and integration test substrate listener
debionetwork/debio-background-worker pull request #112
Opened 2022-07-13 16:54 UTC by rubenkristian

### JIRA LINK
- https://blocksphere2020.atlassian.net/browse/DBIO-2640
- https://blocksphere2020.atlassian.net/browse/DBIO-2563
- https://blocksphere2020.atlassian.net/browse/DBIO-2562
- https://blocksphere2020.atlassian.net/browse/DBIO-2561
- https://blocksphere2020.atlassian.net/browse/DBIO-2560
- https://blocksphere2020.atlassian.net/browse/DBIO-2542
- https://blocksphere2020.atlassian.net/browse/DBIO-2541
- https://blocksphere2020.atlassian.net/browse/DBIO-2520
- https://blocksphere2020.atlassian.net/browse/DBIO-2519
- https://blocksphere2020.atlassian.net/browse/DBIO-2518
- https://blocksphere2020.atlassian.net/browse/DBIO-2515
- https://blocksphere2020.atlassian.net/browse/DBIO-2807

### Changelog
- change from google secret manager to process env
- integration for notification and fix notification
- fix update verification status lab
- fix update lab

### E2E Test Result
- Indexer:
![indexer](https://user-images.githubusercontent.com/56469224/178788437-21b7b21a-cf31-4f16-9931-9b0a997a5584.png)

- Scheduler:
![scheduler](https://user-images.githubusercontent.com/56469224/178788652-b6793baf-d9e0-490b-8565-e67f239f5a1f.png)

- Listener:
![testing ](https://user-images.githubusercontent.com/56469224/178788747-b018569d-7ff8-4935-925d-2174d415e3fd.png)

2022-07-15 02:55 UTC, agustinustheo requested changes

2022-07-15 02:55 UTC, agustinustheo commented on src/listeners/substrate-listener/substrate-listener.handler.ts
> +  }
What is this for?

2022-07-15 03:36 UTC, rubenkristian commented on src/listeners/substrate-listener/substrate-listener.handler.ts
> +  }
it is for unsub event listener

2022-07-16 12:21 UTC, agustinustheo approved these changes

2022-07-16 12:21 UTC, merged