test: integration test genetic analyst
debionetwork/debio-background-worker pull request #139
Opened 2022-08-03 17:34 UTC by rubenkristian

### JIRA LINK
- 

### Changelog
- integration test indexer genetic analyst service
- integration test indexer genetic analyst qualification
- integration test indexer genetic analysis (in process)
- integration test indexer genetic analysis order  (in process)

### E2E Test Result
- Indexer:
- Scheduler:
- Listener:

2022-08-08 03:41 UTC, agustinustheo requested changes

2022-08-08 03:41 UTC, agustinustheo commented on src/indexer/events/genetic-analysis/commands/genetic-analysis-in-progress/genetic-analysis-in-progress.handler.ts
> +    console.log('handler', geneticAnalysisModel, blockMetaData);
Remove this please.

2022-08-08 04:02 UTC, rubenkristian commented on src/indexer/events/genetic-analysis/commands/genetic-analysis-in-progress/genetic-analysis-in-progress.handler.ts
> +    console.log('handler', geneticAnalysisModel, blockMetaData);
Ok

2022-08-16 03:06 UTC, agustinustheo approved these changes

2022-08-16 03:06 UTC, merged