fix: directory template order
debionetwork/debio-background-worker pull request #143
Opened 2022-08-16 07:00 UTC by rubenkristian

### JIRA LINK
- https://blocksphere2020.atlassian.net/browse/DBIO-2865
- https://blocksphere2020.atlassian.net/browse/DBIO-2864

### Changelog
- update package json
- update directory template

### E2E Test Result
- Indexer:
![Screenshot 2022-08-16 134631](https://user-images.githubusercontent.com/56469224/184817220-06514ca8-f7e9-4f84-b2b3-36ed2e276fd2.png)

- Scheduler:
![Screenshot 2022-08-16 134953](https://user-images.githubusercontent.com/56469224/184817240-d01da9fc-829f-418b-879f-80738422a837.png)

- Listener: 
![Screenshot 2022-08-16 131858](https://user-images.githubusercontent.com/56469224/184817194-6078b1b1-ab4b-4577-a6fd-6abcbb825bf5.png)

2022-08-16 07:15 UTC, hilyds approved these changes

2022-08-16 07:19 UTC, agustinustheo approved these changes

2022-08-16 07:20 UTC, agustinustheo requested changes

2022-08-16 07:20 UTC, agustinustheo commented on src/common/mailer/mailer.manager.ts
> +        '../../listeners/substrate-listener/templates/new-order-lab',
Wait this is not supposed to be like this. Why is a `common` module dependent on the `listeners`?

2022-08-18 03:44 UTC, agustinustheo approved these changes

2022-08-18 03:44 UTC, merged