improvement: update transaction hash from blockchain
debionetwork/debio-background-worker pull request #214
Opened 2022-11-14 10:13 UTC by rubenkristian

## Describe your changes
- add transaction_hash to index order when order paid with blockchain hash

## Issue ticket number / link
- https://blocksphere2020.atlassian.net/browse/DBIO-3170

2022-11-17 07:26 UTC, hilyds submitted a review, later dismissed

2022-11-18 02:52 UTC, irmannmal requested changes, later dismissed

2022-11-18 02:52 UTC, irmannmal commented on src/listeners/ethereum-listener/ethereum-listener.handler.ts
> +      // const loggingFulfilled =
please remove this, we have git history

2022-11-18 02:52 UTC, irmannmal commented on src/listeners/ethereum-listener/ethereum-listener.handler.ts
> +      //   await this.transactioLoggingService.updateHash(
and also for this

2022-11-21 00:55 UTC, hilyds approved these changes

2022-11-21 00:56 UTC, merged