[DBIO-2236 & DBIO-2237] Update in indexer genetic analyst event  and unit test
debionetwork/debio-background-worker pull request #92
Opened 2022-03-28 08:18 UTC by rubenkristian

### JIRA LINK 🟦
- https://blocksphere2020.atlassian.net/browse/DBIO-2236
- https://blocksphere2020.atlassian.net/browse/DBIO-2237

### Changelog/Description 🗒️
- update genetic analyst event handler
- update unit test
- update handle eslint warning

### WARNING ⚠️
- 

### Screenshoot/Video (Optional) 🖼️

2022-03-28 08:33 UTC, agustinustheo requested changes
Please check the newest data structure for `GeneticAnalysts` here: https://github.com/debionetwork/debio-node/blob/38ae0c153e50c0c03422940007979fbfd3d7f16f/pallets/genetic-analysts/src/lib.rs#L84-L93

2022-04-05 13:38 UTC, agustinustheo requested changes, later dismissed

2022-04-05 13:38 UTC, agustinustheo commented on src/substrate/models/stake-status.ts
> +  WaitingForStaked = 'WaitingForUnStaked',
`WaitingForUnstaked`?

2022-04-11 12:15 UTC, hilyds approved these changes

2022-04-11 12:16 UTC, merged